# Generated by Django 3.1.5 on 2021-07-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Last_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
