# Generated by Django 3.1.5 on 2021-07-14 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210714_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Last_name',
            new_name='last_name',
        ),
    ]
