# Generated by Django 3.1.5 on 2021-05-13 12:19

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Унікальна Адресса')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('main', ckeditor.fields.RichTextField(blank=True, max_length=600, verbose_name='Короткий текст')),
                ('full', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Повний текст')),
                ('category', models.CharField(choices=[('eco', 'Екологія'), ('bio', 'Біотехнології'), ('mat', 'Матеріалознавство'), ('enr', 'Енергія'), ('all', 'Усі')], default='all', max_length=3, verbose_name='Тематика')),
                ('pub', models.CharField(choices=[('int', 'Внутрішній'), ('ext', 'Зовнішній')], default='int', max_length=3, verbose_name='Публічність')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name="Ім'я")),
                ('surname', models.CharField(max_length=30, verbose_name='Прізвище')),
                ('nameEn', models.CharField(blank=True, max_length=30, verbose_name="Ім'я Англійською")),
                ('surnameEn', models.CharField(blank=True, max_length=30, verbose_name='Прізвище Англійською')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Електронна пошта ')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Телефон')),
                ('phone2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Телефон доп.')),
                ('GoogleDisk', models.URLField(default='#', verbose_name='Посилання на гугл диск')),
                ('Telegram', models.CharField(blank=True, max_length=30, verbose_name='Telegram')),
                ('info', ckeditor.fields.RichTextField(blank=True, max_length=600, verbose_name='Інф.')),
                ('adress', models.CharField(blank=True, max_length=70, verbose_name='Адреса')),
                ('notion', models.CharField(blank=True, max_length=30, verbose_name='Notion')),
                ('linkedIn', models.URLField(blank=True, default='#', verbose_name='Посилання на linkedIn')),
                ('skype', models.CharField(blank=True, max_length=30, verbose_name='Skype')),
                ('fb', models.URLField(blank=True, default='#', verbose_name='Посилання на Facebook')),
                ('clientType', models.CharField(choices=[('pot', 'Потенційний'), ('Внутрішній', (('sud', 'Студент'), ('wor', 'Розробник'))), ('Зовнішній', (('inv', 'Інвестор'), ('ser', 'Надувач сервісу')))], default='pot', max_length=3, verbose_name='Тип партнера')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(blank=True, max_length=40, verbose_name='Установа')),
                ('position', models.CharField(blank=True, max_length=30, verbose_name='Посада')),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='logic.partner')),
            ],
        ),
        migrations.CreateModel(
            name='WorkersTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Назва команди')),
                ('workers', models.ManyToManyField(to='logic.WorkerProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Назва проєкту')),
                ('main', ckeditor.fields.RichTextField(blank=True, max_length=600, verbose_name='Короткий проєкту')),
                ('category', models.CharField(choices=[('eco', 'Екологія'), ('bio', 'Біотехнології'), ('mat', 'Матеріалознавство'), ('enr', 'Енергія'), ('all', 'Усі')], default='all', max_length=3, verbose_name='Тематика')),
                ('projectTeams', models.ManyToManyField(to='logic.WorkersTeam')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('main', ckeditor.fields.RichTextField(blank=True, max_length=250, verbose_name='Тема')),
                ('full', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Опис')),
                ('WorkerProfile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='logic.workerprofile')),
                ('partner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='logic.partner')),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='logic.project')),
                ('rel_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
