# Generated by Django 3.1.5 on 2021-09-01 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsectiontype',
            name='rel_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.project'),
        ),
    ]
