# Generated by Django 3.1.5 on 2021-05-13 18:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='clientType',
        ),
        migrations.AddField(
            model_name='partner',
            name='isInvestor',
            field=models.BooleanField(default=False, verbose_name='Інвестор?'),
        ),
        migrations.AddField(
            model_name='partner',
            name='isPartner',
            field=models.BooleanField(default=False, verbose_name='Партнер?'),
        ),
        migrations.AddField(
            model_name='partner',
            name='isSeviceGiver',
            field=models.BooleanField(default=False, verbose_name='Надавач сервісів?'),
        ),
        migrations.AddField(
            model_name='partner',
            name='isSeviceTaker',
            field=models.BooleanField(default=False, verbose_name='Користувач сервісів?'),
        ),
        migrations.AddField(
            model_name='partner',
            name='isStudent',
            field=models.BooleanField(default=False, verbose_name='Студент?'),
        ),
        migrations.AddField(
            model_name='partner',
            name='isWorker',
            field=models.BooleanField(default=False, verbose_name='Робітник?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='main',
            field=ckeditor.fields.RichTextField(blank=True, max_length=600, verbose_name='Короткий опис проєкту'),
        ),
    ]
