# Generated by Django 3.1.5 on 2021-07-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='indef',
            field=models.CharField(default='basad', editable=False, max_length=10),
            preserve_default=False,
        ),
    ]
