# Generated by Django 3.1.5 on 2021-05-14 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_auto_20210513_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='WorkerProfile',
        ),
    ]
