# Generated by Django 3.1.5 on 2021-07-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0003_auto_20210714_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='GoogleDisk',
            field=models.URLField(blank=True, verbose_name='Посилання на гугл диск'),
        ),
    ]
