# Generated by Django 3.1.5 on 2021-07-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0004_auto_20210714_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='info',
            field=models.TextField(blank=True, max_length=600, verbose_name='Інф.'),
        ),
    ]
