# Generated by Django 3.1.5 on 2021-09-01 22:10

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0004_auto_20210902_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsectionimg',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('img', '400x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='projectsectionimg',
            name='img',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='logic/originals/'),
        ),
    ]
