# Generated by Django 3.1.5 on 2021-09-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0005_auto_20210902_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsectionimg',
            name='cropping',
        ),
        migrations.AlterField(
            model_name='projectsectionimg',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='logic/originals/'),
        ),
    ]
