# Generated by Django 3.1.5 on 2021-07-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0005_auto_20210714_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='valid',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
