# Generated by Django 3.1.5 on 2021-05-18 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0006_auto_20210518_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='workersteam',
            name='rel_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logic.partner', verbose_name='Відповідальна за команду особа'),
        ),
    ]
