# Generated by Django 3.1.5 on 2021-07-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0006_partner_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
