# Generated by Django 3.1.5 on 2021-05-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0007_workersteam_rel_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='isWorker',
            field=models.BooleanField(default=False, verbose_name='Розробник?'),
        ),
    ]
