# Generated by Django 3.1.5 on 2021-09-02 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0007_expertiseanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertiserequest',
            name='rel_Section',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logic.projectsectiontype'),
        ),
    ]
