# Generated by Django 3.1.5 on 2021-05-18 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0008_auto_20210518_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='projectTeams',
        ),
        migrations.AddField(
            model_name='project',
            name='projectTeams',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logic.workersteam', verbose_name="Пов'язана проєктна команда"),
        ),
    ]
