# Generated by Django 3.1.5 on 2021-05-20 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0009_auto_20210518_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='main',
        ),
    ]
