# Generated by Django 3.1.5 on 2021-05-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0010_remove_service_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='full',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='action',
            name='main',
            field=models.TextField(blank=True, max_length=250, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='event',
            name='main',
            field=models.TextField(blank=True, max_length=600, verbose_name='Короткий текст'),
        ),
        migrations.AlterField(
            model_name='service',
            name='target',
            field=models.TextField(blank=True, max_length=600, verbose_name='Цільова аудиторія'),
        ),
        migrations.AlterField(
            model_name='service',
            name='terms',
            field=models.TextField(blank=True, max_length=250, verbose_name='Умови надання'),
        ),
    ]
