# Generated by Django 3.1.5 on 2021-05-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0011_auto_20210520_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectType',
            field=models.CharField(choices=[('teh', 'Технологічні'), ('ser', 'Сервісні')], default='teh', max_length=3, verbose_name='Тип проєкту'),
        ),
    ]
