# Generated by Django 3.1.5 on 2021-05-25 19:26

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('logic', '0012_project_projecttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipientservices',
            name='partnerTags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Список зацікавивших тегів'),
        ),
        migrations.AddField(
            model_name='service',
            name='partnerTags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Список тегів сервісу'),
        ),
    ]
